# Generated by Django 2.0.13 on 2019-05-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='garbage', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_nail',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
