# Generated by Django 2.0.13 on 2019-05-25 07:49

from django.db import migrations
import django.utils.timezone
import django_markdownx.markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190523_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_markdownx.markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
