# Generated by Django 2.0.13 on 2019-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190525_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='hello!', max_length=200),
        ),
    ]
