# Generated by Django 2.0.13 on 2019-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ABOUT', 'about'), ('POSTS', 'posts'), ('ALGORITHM', 'algorithms'), ('HACKING', 'hacking'), ('EATING', 'eating')], default='about', max_length=100),
        ),
    ]
